services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        # image: laravel-app:latest
        container_name: gac-app
        restart: unless-stopped
        volumes:
            - ./:/var/www/html
            # Exclude the vendor directory from host to avoid conflicts and use container's vendor
            - /var/www/html/vendor
        networks:
            - gac_network
        depends_on:
            - db
        ports:
            - "8000:80" # Map host port 8000 to container port 80 (Nginx)
        environment:
            - APP_KEY=${APP_KEY}
            - APP_ENV=${APP_ENV}
            - APP_DEBUG=${APP_DEBUG}
            - APP_URL=${APP_URL}
            - DB_CONNECTION=${DB_CONNECTION}
            - DB_HOST=${DB_HOST}
            - DB_DATABASE=${DB_DATABASE}
            - DB_USERNAME=${DB_USERNAME}
            - DB_PASSWORD=${DB_PASSWORD}
    db:
        image: mysql:8.4
        container_name: gac-db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        ports:
            - "3306:3306"
        volumes:
            - db-data:/var/lib/mysql
        networks:
            - gac_network
volumes:
    db-data:
networks:
    gac_network:
        driver: bridge
