services:
    # PHP-FPM service (using the image built from your Dockerfile)
    app:
        build:
            context: .
            dockerfile: Dockerfile
        #image: game-ako-chronicles-blog:latest # Use the image name you built
        container_name: gac_app
        restart: unless-stopped
        volumes:
            - storage:/usr/share/nginx/html/storage:rw
            - public:/usr/share/nginx/html/public:rw
            # - .:/var/www # Mount your project directory for development (optional for production)
            # - /var/www/vendor # Keep vendor outside the bind mount to avoid host permissions issues
            # - ./docker-entrypoint.sh:/usr/local/bin/docker-entrypoint.sh # Mount the custom entrypoint
        # Specify the custom entrypoint script.
        # This will be executed when the container starts.
        #entrypoint: ["docker-entrypoint.sh"]
        ports:
            - "9000:9000" # Expose PHP-FPM port (not directly accessed by browser)
        environment:
            # Set your Laravel environment variables here
            # IMPORTANT: For production, use Azure App Service environment settings or Key Vault
            APP_ENV: production
            APP_DEBUG: "false"
            APP_URL: http://localhost
            DB_CONNECTION: mysql
            DB_HOST: db # This matches the service name of your MySQL container
            DB_PORT: 3306
            DB_DATABASE: ${DB_DATABASE}
            DB_USERNAME: ${DB_USERNAME}
            DB_PASSWORD: ${DB_PASSWORD}
        # env_file:
        #     - .env
        depends_on:
            - db

    # Nginx web server
    nginx:
        image: nginx:alpine
        container_name: gac_nginx
        restart: unless-stopped
        ports:
            - "80:80" # Expose port 80 for web access
            # - "443:443" # https
        volumes:
            #- .:/var/www # Mount your project directory
            #- ./nginx.conf:/etc/nginx/templates/default.conf.template
            - ./nginx.conf:/etc/nginx/conf.d/default.conf # Mount your custom Nginx config
            - storage:/usr/share/nginx/html/storage:rw
            - public:/usr/share/nginx/html/public:ro
        depends_on:
            - app # Nginx depends on the PHP-FPM app service

    # MySQL database
    db:
        image: mysql:8.4 # Using MySQL 8.4 as requested
        container_name: gac_db
        restart: unless-stopped
        ports:
            - "3306:3306" # Expose MySQL port (optional, for local access)
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD} # Set a strong root password
        volumes:
            - dbdata:/var/lib/mysql # Persist database data

volumes:
    dbdata: # Named volume for MySQL data persistence
    storage:
    public:
